    <h1>About this project</h1>

    <div id="more-information">
        <p><img src="http://framework.zend.com/images/PoweredBy_ZF_4LightBG.png" /></p>
        <p>ZF version: <?php echo $this->zfversion ?></p>
        <p>PHP version: <?php echo $this->phpversion ?></p>
        <p>Layout uses <a href="http://getbootstrap.com/">Bootstrap 3.3.2</a> - starter template.</p>
    </div>
    <div>
    <p>Programming by Sheila Fenelon (sheila@shefen.com)</p>
    <p>March 2015</p>
    
    </div>
