<div class="panel panel-default">
  <div class="panel-heading"><h2>Edit this Country</h2></div>

  <div class="row">
    
    <div class="col-md-4"></div>
    <div class="col-md-4 text-left">
    
<?php 
echo $this->form;
?>

    </div>
    <div class="col-md-4"></div>
  </div>
</div>

<?php /* 
<pre>
Code: <?php echo $this->code; ?>
<?php var_dump($this->countryModel); ?>
<?php var_dump($this->formdata); ?>
</pre>
*/?>