<?php 
if (isset($this->messages)) {
    echo '<p class="text-left text-info">'. join('<br>', $this->messages) . '</p>';
}
?>


<h2>List of Countries in Database</h2>

<div class="panel panel-default">
    <div class="panel-heading">Number of countries in the database: <?php echo count($this->countries); ?> </div>



<table id="data" class="table">
<tr>
  <th>Country</th>
  <th>
<?php if ($this->isAuthenticated()) { ?>
  <form action="/index/addcountry"><button class="btn-primary" >Add Another Country</button></form>
<?php } else { ?>   
  &nbsp;
<?php } ?> 
  </th>
</tr>

<?php foreach ($this->countries as $c): ?>

    <tr>
       <td align="left"><?php echo $this->escape($c->getName()) ?></td>
       <td>
         <form action="/index/view/<?php echo $c->getCode()?>"><button class="btn-primary" >View Details</button>
<?php if ($this->isAuthenticated()) { ?>
         &nbsp;
         <button formmethod='get' formaction="/index/editcountry/<?php echo $c->getCode()?>" class="btn-primary" >Edit</button>
         &nbsp;
         <button
         		formaction='#'
         		data-url='/index/delcountry/' 
         		data-toggle="modal" 
         		data-target="#confirmdeletecountry"
                data-countryname="<?php echo $this->escape($c->getName()) ?>"
                data-countrycode="<?php echo $this->escape($c->getCode()) ?>"
                class="btn-primary" >Delete</button>
         </form>
<?php } ?> 
         
       </td>
    </tr>
    
<?php endforeach ?>

</table>
    
</div>


<div class="modal fade" id="confirmdeletecountry" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
    
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="modalLabel">Confirm Delete</h4>
      </div>
      
      <div class="modal-body">
            <p>Are you sure you want to delete this country?</p>
            <p class='debug-url'></p>
      </div>
      
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <a class="btn btn-danger btn-ok">Yes, remove it</a>
      </div>
      
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
