<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <?php 
    $this->headTitle($this->title)->setSeparator(' - ');
    echo $this->headTitle();
    ?>

    <!-- Bootstrap -->
    <link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/bootstrap/css/custom.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

  <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/index/">World DB</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li <?php if ($this->current == 'index') { echo 'class="active"'; }?>><a href="/index/">Home</a></li>
            <li <?php if ($this->current == 'about') { echo 'class="active"'; }?>><a href="/index/about">About</a></li>
        <?php if ($this->isAuthenticated()) { ?>
            <li <?php if ($this->current == 'auth') { echo 'class="active"'; }?>><a href="/auth/logout">Logout</a></li>
        <?php } else { ?> 
            <li <?php if ($this->current == 'auth') { echo 'class="active"'; }?>><a href="/auth/login">Login</a></li>
        <?php }?>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">
        <div class="content">
<?php echo $this->layout()->content ?>
        </div>
    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="/bootstrap/js/bootstrap.min.js"></script>

<?php /* TODO: add these scripts just on the pages where they are used.  */?>
    
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery-form-validator/2.1.47/jquery.form-validator.min.js"></script>

<script> 
    $.validate({
    	form : '#login',
    	borderColorOnError : '#F00',
  	    addValidClassOnAll : true
    }); 
</script>
    
<script>

$('#confirmdeletecountry').on('show.bs.modal', function (event) {
	  var button = $(event.relatedTarget) // Button that triggered the modal
	  var countryname = button.data('countryname') 
	  var url = button.data('url')
	  var code = button.data('countrycode')
	  
	  var modal = $(this)
	  modal.find('.modal-title').text('Delete ' + countryname + '?')
	  // set the ok button to the url for delete action
	  $(this).find('.btn-ok').attr('href', url + code)
	  
	  //$('.debug-url').html('Delete URL: <strong>' + url + code + '</strong>')
});
	
</script>
    
    
  </body>
</html>
